name: CI
on:
  pull_request:
  push:
    branches:
      - master
    tags: '*'
# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'lts'  # lts
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - name: Configure GDAL libraries and certificates on macOS
        id: macos-gdal
        if: runner.os == 'macOS'
        shell: julia --color=yes --project {0}
        run: |
          using GDAL, NetworkOptions
          # SQLite_jll's newer install name differs from the one GDAL links to.
          # Resolve that dependency to the JLL library instead of Apple's SQLite.
          open(ENV["GITHUB_OUTPUT"], "a") do io
              println(io, "sqlite_libdir=", dirname(GDAL.GDAL_jll.SQLite_jll.libsqlite_path))
          end
          # GDAL's libcurl needs a file even when Julia uses the system trust store.
          open(ENV["GITHUB_ENV"], "a") do io
              println(io, "CURL_CA_BUNDLE=", NetworkOptions.ca_roots_path())
          end
      - uses: julia-actions/julia-runtest@v1
        with:
          # Set DYLD_LIBRARY_PATH after bash starts: macOS can strip inherited DYLD variables.
          prefix: ${{ runner.os == 'macOS' && format('env DYLD_LIBRARY_PATH={0}', steps.macos-gdal.outputs.sqlite_libdir) || '' }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v7
        with:
          files: lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: 'lts'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Fetch files for documentation examples
        run: julia --project=docs/ test/remotefiles.jl
      - name: Build and deploy documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
          GKSwstype: "100" # https://discourse.julialang.org/t/generation-of-documentation-fails-qt-qpa-xcb-could-not-connect-to-display/60988
        run: julia --project=docs/ docs/make.jl
